name: Practise Project
on: [push,workflow_dispatch]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@4
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Perform lint
              run: npm run lint
            - name: Run Echo
              run: echo "Linting Completed"
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run Test
              run: npm run test
            - name: Run Echo
              run: echo "Testing Completed"
    build:
        runs-on: Ubuntu-latest
        needs: [lint,test]
        steps:
            - name: Get Code
              uses : actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Run Build
              run: npm run build
            - name: Run Echo
              run: echo "build completed"
              